-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."terrain_hex_palette" add column "name" text
--  not null unique;
