-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- UPDATE npc
-- SET image_url = '/races/nomads.png'
-- WHERE id = 'b01a69e5-aedc-421c-8a4c-8b729e5338a2';
