-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."resource_generator" add column "resource_type_id" uuid
--  not null;
