-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."galactic_empire_resource_generator" add column "count" numeric
--  not null default '1';
