-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."galactic_empire" add column "res_energy_capacity" integer
--  not null;
