-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."resource_type" add column "order" integer
--  not null default '0';
