-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- UPDATE background
-- SET image_url = '/backgrounds/flavour/prospector.png'
-- WHERE id = 'eac2eab5-fba4-44a3-b57e-1d7ac1f341c3';
