-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."quest_reward" add column "resource_accrual_type_id" uuid
--  null;
