-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."galactic_empire" add column "celestial_claims" integer
--  not null default '0';
