-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."resource_generator" add column "cost_growth_exponent" numeric
--  not null default '1.5';
