-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- UPDATE faction
-- SET description = 'After the reverse-engineering project of the Ancient tech that resulted in FTL comms, some engineers working on deep-space satellites received a repeating message in the Ancient language for a few days until it suddenly stopped. The message simply read: ''DO NOT TRUST THEM'', along with FTL comm coordinates that seemingly go nowhere.<br/><br/> After receiving this message, the UNC on Terra sent a message to the Ancients, and received only a warning in return: ''NEVER attempt to communicate with the Nihils.'''
-- WHERE id = '98498f69-ea69-4524-b251-54df78ba53a7';
