-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."resource_generator_type" add column "unlocked_by_technology_id" uuid
--  null;
