-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."galactic_empire_resources" add column "galactic_empire_id" uuid
--  not null;
