-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- UPDATE playable_race
-- SET description = 'The Nomads, a race of inter-planetary traders, thrive on Aridus, a barren desert planet, utilizing their trade expertise to prosper in harsh conditions. They oversee commerce in a federation of planets, skilled in market understanding and negotiation. Proud and independent, they value freedom and survival, with the leading family, the Sanimas, relocating from Earth to Aridus, a move shrouded in mystery. Secrets of Aridus await discovery.'
-- WHERE id = '98f22f43-e36c-4b0c-9554-b13af42de556';
