-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."galactic_empire_quest" add column "quest_step_id" uuid
--  not null;
