// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package idleversedata

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// Playable backgrounds
type Background struct {
	ID          pgtype.UUID
	Name        string
	Description string
	ImageUrl    pgtype.Text
}

type Celestial struct {
	Name             pgtype.Text
	GalaxyID         pgtype.UUID
	OwnerID          pgtype.Text
	ID               string
	GalacticEmpireID pgtype.UUID
	FormingPoints    pgtype.Numeric
}

type ChatMessage struct {
	ID        pgtype.UUID
	Message   string
	PosterID  string
	Timestamp pgtype.Timestamp
}

// NPC factions
type Faction struct {
	ID          pgtype.UUID
	Name        string
	Description string
	ImageUrl    pgtype.Text
}

type GalacticEmpire struct {
	ID              pgtype.UUID
	UserID          string
	GalaxyID        pgtype.UUID
	BackgroundID    pgtype.UUID
	FactionID       pgtype.UUID
	PlayableRaceID  pgtype.UUID
	HomeworldID     pgtype.UUID
	CelestialClaims int32
}

// NPCs unlocked for this empire
type GalacticEmpireNpc struct {
	NpcID            pgtype.UUID
	ID               pgtype.UUID
	GalacticEmpireID pgtype.UUID
}

type GalacticEmpireQuest struct {
	ID               pgtype.UUID
	GalacticEmpireID pgtype.UUID
	QuestID          pgtype.UUID
	Completed        bool
	QuestStepID      pgtype.UUID
}

type GalacticEmpireResource struct {
	ResourceTypeID   pgtype.UUID
	Value            int32
	UpdatedAt        pgtype.Timestamptz
	ID               pgtype.UUID
	GalacticEmpireID pgtype.UUID
}

type GalacticEmpireResourceGenerator struct {
	ID               pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	GalacticEmpireID pgtype.UUID
	GeneratorTypeID  pgtype.UUID
	PlanetID         pgtype.UUID
	Count            pgtype.Numeric
}

type Galaxy struct {
	ID                      pgtype.UUID
	Name                    pgtype.Text
	Radius                  int32
	Arms                    pgtype.Numeric
	Curvature               pgtype.Numeric
	ArmWidth                pgtype.Numeric
	CoreRadiusFactor        pgtype.Numeric
	CoreConcentrationFactor pgtype.Numeric
	Stars                   int32
}

type HdbCatalogHdbActionLog struct {
	ID                 pgtype.UUID
	ActionName         pgtype.Text
	InputPayload       []byte
	RequestHeaders     []byte
	SessionVariables   []byte
	ResponsePayload    []byte
	Errors             []byte
	CreatedAt          pgtype.Timestamptz
	ResponseReceivedAt pgtype.Timestamptz
	Status             string
}

type HdbCatalogHdbCronEvent struct {
	ID            string
	TriggerName   string
	ScheduledTime pgtype.Timestamptz
	Status        string
	Tries         int32
	CreatedAt     pgtype.Timestamptz
	NextRetryAt   pgtype.Timestamptz
}

type HdbCatalogHdbCronEventInvocationLog struct {
	ID        string
	EventID   pgtype.Text
	Status    pgtype.Int4
	Request   []byte
	Response  []byte
	CreatedAt pgtype.Timestamptz
}

type HdbCatalogHdbMetadatum struct {
	ID              int32
	Metadata        []byte
	ResourceVersion int32
}

type HdbCatalogHdbScheduledEvent struct {
	ID            string
	WebhookConf   []byte
	ScheduledTime pgtype.Timestamptz
	RetryConf     []byte
	Payload       []byte
	HeaderConf    []byte
	Status        string
	Tries         int32
	CreatedAt     pgtype.Timestamptz
	NextRetryAt   pgtype.Timestamptz
	Comment       pgtype.Text
}

type HdbCatalogHdbScheduledEventInvocationLog struct {
	ID        string
	EventID   pgtype.Text
	Status    pgtype.Int4
	Request   []byte
	Response  []byte
	CreatedAt pgtype.Timestamptz
}

type HdbCatalogHdbSchemaNotification struct {
	ID              int32
	Notification    []byte
	ResourceVersion int32
	InstanceID      pgtype.UUID
	UpdatedAt       pgtype.Timestamptz
}

type HdbCatalogHdbVersion struct {
	HasuraUuid     pgtype.UUID
	Version        string
	UpgradedOn     pgtype.Timestamptz
	CliState       []byte
	ConsoleState   []byte
	EeClientID     pgtype.Text
	EeClientSecret pgtype.Text
}

// non-playable characters
type Npc struct {
	ID        pgtype.UUID
	Name      string
	RaceID    pgtype.UUID
	FactionID pgtype.UUID
	ImageUrl  string
}

type Planet struct {
	ID                  pgtype.UUID
	CelestialID         string
	Radius              pgtype.Numeric
	TextureResolution   int32
	TerrainBias         []pgtype.Numeric
	TerrainHexPaletteID pgtype.UUID
	OwnerID             string
	Name                string
	AtmosphericDistance pgtype.Numeric
	OrbitalRadius       pgtype.Numeric
}

type PlanetaryRing struct {
	ID          pgtype.UUID
	Rotation    []pgtype.Numeric
	Type        string
	Colors      []string
	TerrainBias []pgtype.Numeric
	InnerRadius pgtype.Numeric
	OuterRadius pgtype.Numeric
	Resolution  int32
}

// Playable races
type PlayableRace struct {
	ID          pgtype.UUID
	Name        string
	Description string
	ImageUrl    pgtype.Text
}

type Quest struct {
	ID               pgtype.UUID
	Name             string
	Description      string
	Type             string
	NextQuestInChain pgtype.UUID
	Initial          pgtype.Bool
	ImageUrl         pgtype.Text
}

type QuestReward struct {
	ID                    pgtype.UUID
	QuestID               pgtype.UUID
	Type                  string
	ResourceAccrualTypeID pgtype.UUID
	ResourceAccrualAmount pgtype.Int4
	NpcUnlockID           pgtype.UUID
	ResourceUnlockID      pgtype.UUID
}

type QuestRewardType struct {
	Value       string
	Description string
}

type QuestStep struct {
	ID                 pgtype.UUID
	Description        string
	Type               string
	QuestID            pgtype.UUID
	NpcContactID       pgtype.UUID
	ResourceCostID     pgtype.UUID
	ResourceCostAmount pgtype.Int4
	NextStepInQuest    pgtype.UUID
	Initial            bool
}

type QuestStepType struct {
	Value       string
	Description string
}

type QuestType struct {
	Value string
}

type ResourceGenerator struct {
	ID                     pgtype.UUID
	Name                   string
	Description            string
	GenerationRate         []pgtype.Numeric
	ImageUrl               pgtype.Text
	ResourceType1ID        pgtype.UUID
	ResourceType2ID        pgtype.UUID
	UnlockedByTechnologyID pgtype.UUID
	CostResourceTypeID1    pgtype.UUID
	CostAmount1            pgtype.Numeric
	CostGrowthExponent     pgtype.Numeric
}

type ResourceType struct {
	ID            pgtype.UUID
	Type          string
	ImageUrlPixel pgtype.Text
	ImageUrl      pgtype.Text
}

type Technology struct {
	ID           pgtype.UUID
	Name         string
	Description  pgtype.Text
	Children     []pgtype.UUID
	Root         pgtype.Bool
	ResearchCost int32
	ImageUrl     pgtype.Text
}

type TerrainHexPalette struct {
	Water  string
	Sand   string
	Grass  string
	Forest string
	ID     pgtype.UUID
	Name   string
}

type UserInfo struct {
	ID                string
	Nickname          string
	SecretSettingTest pgtype.Text
	Name              pgtype.Text
	DisplayName       pgtype.Text
	FreeClaims        int32
	AvatarUrl         pgtype.Text
}

type UserMe struct {
	ID                string
	Nickname          string
	SecretSettingTest pgtype.Text
	Name              pgtype.Text
	DisplayName       pgtype.Text
	FreeClaims        int32
	AvatarUrl         pgtype.Text
}

type UserPrivate struct {
	UserID            string
	SecretSettingTest pgtype.Text
}
