-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."technology" add column "research_cost" integer
--  not null default '0';
